# Generated by Django 3.1.7 on 2021-04-07 17:45

import Post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_videopost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='video',
            field=models.FileField(upload_to=Post.models.user_directory_path),
        ),
    ]
